### ISSUE TITLE
Cookies Logo

### ISSUE THREAD

**Issue by fireantrescue** [emspace-io/emspace-io.github.io#101]
Needs to be resized on the pdf and on the secondary page

**Comment by fireantrescue** [comment]
Okay guy, can you compress and replace these?
![05-11](https://cloud.githubusercontent.com/assets/7229017/12978231/41df8d72-d095-11e5-8999-6560b1a3ebd0.png)
![05-09](https://cloud.githubusercontent.com/assets/7229017/12978232/41e11d22-d095-11e5-9ae1-6197d538bed6.png)

**Comment by keegnotrub** [comment]
Replaced.
