### ISSUE TITLE
Consider changing from modernizer to just html5shiv for simplicity

### ISSUE THREAD

**Issue by keegnotrub** [emspace-io/emspace-io.github.io#103]
https://github.com/aFarkas/html5shiv

Can be downloaded directly here:

https://github.com/aFarkas/html5shiv/archive/master.zip

Or perhaps even better switch from Google provider jQuery to using something like cdnjs in order to search and find javascript to use as it might become a better resource for beginners to learn about?

**Comment by fireantrescue** [comment]
Should we include a note lining people to our Elbongurk article on Modernizr?

**Comment by keegnotrub** [comment]
I think for now Modernizr just complicates what we are going for with the least amount of info possible to be dangerous.
