### ISSUE TITLE
My List of Complaints - Ryan Please Review

### ISSUE THREAD

**Issue by fireantrescue** [emspace-io/emspace-io.github.io#105]
L2- Why is fig. 6 a screenshot of TextMate? Could this just be a regular code example since the next time I say to check the HTML (later in the same lesson) it is just a regular code example?

L11- weird red boxes around ‘ in the `@font-face` code example

L12- In sentence above Floating Columns, the quotation marks are facing the wrong way.

L18- red box in code example above fig. 7, fig 8, fig. 11, 13, 14

**Comment by keegnotrub** [comment]
Moved first item to #115 and then did the rest.
