### ISSUE TITLE
Three dots to indicate more code...

### ISSUE THREAD

**Issue by fireantrescue** [emspace-io/emspace-io.github.io#108]
We need to do a sweep to see where and when we need to use three dots to indicate more or less code.

**Comment by fireantrescue** [comment]
I tried to tackle this one on 3-7-16. I think the HTML is good but I wasn't sure about the consistent application of the dots on the CSS examples. One more go round maybe?

**Comment by keegnotrub** [comment]
I think this is good enough for me now.
