### ISSUE TITLE
Use screenshots for html examples

### ISSUE THREAD

**Issue by keegnotrub** [emspace-io/emspace-io.github.io#56]
* Lesson 2 has a paragraph: "In HTML we can call out strongly emphasized text by wrapping that text we want to emphasize in a set of special tags" which would be better as a screenshot
* Lesson 2 has a "Lesson Two - HTML Semantic Text" heading that would probably be better as a screenshot.  
* Lesson 4 has some definition lists that would probably be better as a screenshot.  
* The forms lesson would benefit from screenshots as well.
* L5- I need the text link example to have an underline (right above heading Image Links)

**Comment by fireantrescue** [comment]
Here they are. You need to smush them and then put them in place.
<img width="306" alt="checkboxes" src="https://cloud.githubusercontent.com/assets/7229017/13206161/498cdac6-d8be-11e5-820c-0cc3a255e776.png">
<img width="416" alt="definition-list" src="https://cloud.githubusercontent.com/assets/7229017/13206162/498f085a-d8be-11e5-9302-61adc5eb72b6.png">
<img width="418" alt="description-list" src="https://cloud.githubusercontent.com/assets/7229017/13206166/4991f9de-d8be-11e5-8752-5298ef93fd2c.png">
<img width="119" alt="dropdown" src="https://cloud.githubusercontent.com/assets/7229017/13206165/49918c1a-d8be-11e5-8a36-d1acbe56107f.png">
<img width="501" alt="emphasized-text" src="https://cloud.githubusercontent.com/assets/7229017/13206164/49916898-d8be-11e5-9315-593f482d051c.png">
<img width="133" alt="radio-buttons" src="https://cloud.githubusercontent.com/assets/7229017/13206163/49900868-d8be-11e5-9a74-58623f84898d.png">
<img width="496" alt="strong" src="https://cloud.githubusercontent.com/assets/7229017/13206168/499beade-d8be-11e5-9d58-5d042abe1a78.png">
<img width="68" alt="submit" src="https://cloud.githubusercontent.com/assets/7229017/13206167/499aa48a-d8be-11e5-9edd-a38652ed7ea2.png">
<img width="187" alt="text-field" src="https://cloud.githubusercontent.com/assets/7229017/13206170/499f93e6-d8be-11e5-8ae9-b49a1ead80a7.png">
<img width="80" alt="text-link" src="https://cloud.githubusercontent.com/assets/7229017/13206169/499d81fa-d8be-11e5-956b-398979ec5bda.png">
<img width="181" alt="textarea" src="https://cloud.githubusercontent.com/assets/7229017/13206171/499f98c8-d8be-11e5-8b1c-53661bfbc4a7.png">

**Comment by fireantrescue** [comment]
Fixed. Note: I did add pixels to the bottom of my screenshots (50 total height, most on the bottom) on the screenshot as well as set the background to #f8f8f8 to match the figure background.

**Comment by fireantrescue** [comment]
[temp.zip](https://github.com/emspace-io/emspace-io.github.io/files/145535/temp.zip)

um. I'm not sure if this attached but it is a zip file of the root folder that holds the html/css that generates the file for these screenshots. We can use it when we need 2X files if we want.
