### ISSUE TITLE
In Box Model, consider removing figure 20

### ISSUE THREAD

**Issue by keegnotrub** [emspace-io/emspace-io.github.io#61]
I think the point has already been made and that including that diagram almost might overwhelm the reader.

**Comment by fireantrescue** [comment]
I'm fine with that. Let's eliminate it.

We can delete from: 

_**I’ve made a diagram of the box model to help describe what is happening. (fig. 20)**_

through:

_**The diagram shows each component part of the box and the default setting. Notice that the default setting is typically 0;, with the exception of the margin which we discovered earlier. Almost everything by default has some white space around it to make things easy to read even if a stylesheet is never used.**_

Then, we'll need to renumber fig. 21 and 22 in both the text and the images.

**Comment by keegnotrub** [comment]
Done.
