### ISSUE TITLE
Give HTML example for adding group class to header to contain float

### ISSUE THREAD

**Issue by keegnotrub** [emspace-io/emspace-io.github.io#74]
In Creating Navigation for the Big Screen, around line 465, we add a group class to the to clear fix on the float but we don't show what the resulting HTML will look like.

**Comment by fireantrescue** [comment]
I added the HTML example, but without actually doing the lesson (which I will do) it's difficult to know how much code to include. For now I have just the opening header tag with is already in the numbered instructions so it's pretty redundant. I'll add more once we fix the max-width issues.

Also, this caused a numbering problem. I need the following "1. Locate your CSS" to actually be 4. Locate your CSS to continue the numbering from above.

**Comment by keegnotrub** [comment]
Fixed.
