### ISSUE TITLE
No Windows Code Editor!

### ISSUE THREAD

**Issue by fireantrescue** [emspace-io/emspace-io.github.io#83]
I need a code editor option for my Windows friends. Could be Brackets, but I could also use the Windows version of TextEdit if I can figure out the correct settings.

**Comment by keegnotrub** [comment]
Being that TextMate kind of bills itself as TextEdit plus.  Maybe we should consider recommending Notepad++ on Window, which bills itself as Notepad (the default Windows simple text editor) plus.  Notepad++ is also open source similar to TextMate.

**Comment by fireantrescue** [comment]
I have made a series of screenshots for Notepad++. Most of them are Blog > Notepad > crops but a few on on my H drive at work. I'll pick that up and add those to the mix. I'm planning to add the setup as a blog post on elbongurk and just linking to it from L1 by adding this line to the lesson:

In order to write code, you’ll need special software specifically designed for coding websites. There are many great options out there but for this book, I’m going to be using TextMate. This is a open source program for Mac and can be downloaded and installed here: TextMate 2.0 beta. *For anyone using Windows, I recommend using [Notepad++](https://notepad-plus-plus.org), a very similar open source program made for Windows. For complete installation instructions and configuration, I've written a blog post available [here](not yet written).
