### ISSUE TITLE
Call out Paragraph

### ISSUE THREAD

**Issue by fireantrescue** [emspace-io/emspace-io.github.io#86]
There is a paragraph in the Emphasized and Strongly Emphasized Text section that needs to be called out because it isn't part of the body text:

In HTML we can call out strongly emphasized text by wrapping that text we want to emphasize in a set of special tags

Is there a way to set this guy apart? Maybe an outdent?

**Comment by fireantrescue** [comment]
This is also the case for the next paragraph. It's supposed to look like an h1 but doesn't really look like the browser default:

Lesson Two - HTML Semantic Text

We need to take a look at this guy as well.

**Comment by keegnotrub** [comment]
Noted in #56
