### ISSUE TITLE
Consistency about using 0X or X in Lesson title

### ISSUE THREAD

**Issue by keegnotrub** [emspace-io/emspace-io.github.io#99]
In lessons 2, 4, and 9 we use "Lesson X - Title of Lesson" but in lessons 3, 5, 7, & 9 we use "Lesson 0X - Title of Lesson". We should probably be consistent here.

Additionally, lesson 3 is missing a space between its dash in the title.

Somebody also had a big quotation mark at the end. Probably L15 since that one is always a hot mess.

**Comment by fireantrescue** [comment]
We eliminated all lesson titles in the content of all lessons or at least I hope we did.
